export const ApiUrl = {
    get:"get-otp-api/",
    verify:"verify-otp/",
    sign:"signup/",
    matched :"updatepreference/",
    manage : "adminapp/preferenceupdate-by-admin/",
    status: "adminapp/profile-active-and-deactive-by-admin/",
    blog: "adminapp/blog-category-api-of-admin/",
    add: "adminapp/blog-api-of-admin/",
    faq: "adminapp/faq-admin-api/",
    plan: "adminapp/planmodule-by-admin/",
    module : "adminapp/plan_by_admin/",
    history: "adminapp/user-plan-history/",
    count: "adminapp/profile-visitors-report/",
    profile: "adminapp/profile-verification-api/",
    visitor: "adminapp/user-plan-history-report/",
    common: "adminapp/most-common-search-criteria/",
    chat: "adminapp/get-chat-messages-by-profile/",
    hobby: "adminapp/user-hobbies-report/",
    image: "adminapp/user-profile-image-report/",
    historyreport: "adminapp/request-history-report/",
    planreport: "adminapp/user-without-plan-report/"
}